"""empty message

Revision ID: 924fd6a7974a
Revises: 
Create Date: 2025-03-19 00:57:47.174560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924fd6a7974a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city')
    )
    op.create_table('forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('temperature', sa.String(length=10), nullable=True),
    sa.Column('humidity', sa.String(length=4), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('wind_speed', sa.String(length=10), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city_weather.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast')
    op.drop_table('city_weather')
    # ### end Alembic commands ###
